/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Cta = {
  label?: string;
  href?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Icon = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type Included = {
  _type: "included";
  eyebrow?: string;
  title?: string;
  introText?: string;
  items?: Array<string>;
};

export type Offerings = {
  _type: "offerings";
  eyebrow?: string;
  title?: string;
  introText?: string;
  offerings?: Array<{
    tag?: string;
    title?: string;
    description?: string;
    features?: Array<string>;
    _key: string;
  }>;
};

export type ServicesHero = {
  _type: "servicesHero";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  introText?: string;
  ctas?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
};

export type Credentials = {
  _type: "credentials";
  eyebrow?: string;
  title?: string;
  introText?: string;
  credentials?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type Principles = {
  _type: "principles";
  eyebrow?: string;
  title?: string;
  introText?: string;
  principles?: Array<{
    label?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type MyStory = {
  _type: "myStory";
  eyebrow?: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  quote?: string;
  quoteLabel?: string;
};

export type AboutHero = {
  _type: "aboutHero";
  eyebrow?: string;
  title?: string;
  titleHighlight?: string;
  introText?: string;
  cta?: Cta;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    name?: string;
    detail?: string;
    _type: "image";
  };
};

export type Contact = {
  _type: "contact";
  eyebrow?: string;
  title?: string;
  introText?: string;
  details?: Array<{
    icon?: Icon;
    label?: string;
    text?: string;
    href?: string;
    _key: string;
  }>;
};

export type Proof = {
  _type: "proof";
  eyebrow?: string;
  title?: string;
  introText?: string;
  testimonials?: Array<{
    name?: string;
    quote?: string;
    label?: string;
    _key: string;
  }>;
};

export type Method = {
  _type: "method";
  eyebrow?: string;
  title?: string;
  sideNote?: string;
  methods?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type FirstWeeks = {
  _type: "firstWeeks";
  eyebrow?: string;
  title?: string;
  introText?: string;
  steps?: Array<{
    marker?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type About = {
  _type: "about";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  eyebrow?: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  listTitle?: string;
  credentials?: Array<string>;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  title?: string;
  introText?: string;
  ctas?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    name?: string;
    role?: string;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  navLinks?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  contactButton?: {
    label?: string;
    href?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Array<
    | ({
        _key: string;
      } & ServicesHero)
    | ({
        _key: string;
      } & Offerings)
    | ({
        _key: string;
      } & Included)
    | ({
        _key: string;
      } & Contact)
  >;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Array<
    | ({
        _key: string;
      } & AboutHero)
    | ({
        _key: string;
      } & MyStory)
    | ({
        _key: string;
      } & Method)
    | ({
        _key: string;
      } & Principles)
    | ({
        _key: string;
      } & Credentials)
    | ({
        _key: string;
      } & Contact)
  >;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & About)
    | ({
        _key: string;
      } & FirstWeeks)
    | ({
        _key: string;
      } & Method)
    | ({
        _key: string;
      } & Proof)
    | ({
        _key: string;
      } & Contact)
  >;
  seo?: {
    title?: string;
    description?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Cta
  | SanityImageAssetReference
  | Icon
  | Included
  | Offerings
  | ServicesHero
  | Credentials
  | Principles
  | MyStory
  | AboutHero
  | Contact
  | Proof
  | Method
  | FirstWeeks
  | About
  | Hero
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | ServicesPage
  | AboutPage
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/components/header/index.tsx
// Variable: NAV_QUERY
// Query: *[_id == "siteSettings"][0]{    logo{ alt, "url": asset->url },    navLinks[]{ _key, label, href },    contactButton{ label, href }  }
export type NAV_QUERY_RESULT =
  | {
      logo: null;
      navLinks: null;
      contactButton: null;
    }
  | {
      logo: {
        alt: string | null;
        url: string | null;
      } | null;
      navLinks: Array<{
        _key: string;
        label: string | null;
        href: string | null;
      }> | null;
      contactButton: {
        label: string | null;
        href: string | null;
      } | null;
    }
  | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    sections[]{      _key,      _type,      _type == "hero" => {        eyebrow,        title,        introText,        ctas[]{ _key, label, href },        image{ alt, name, role, asset }      },      _type == "about" => {        eyebrow,        title,        body,        listTitle,        credentials,        image{ alt, caption, asset }      },      _type == "firstWeeks" => {        eyebrow,        title,        introText,        steps[]{ _key, marker, title, description }      },      _type == "method" => {        eyebrow,        title,        sideNote,        methods[]{ _key, title, description }      },      _type == "proof" => {        eyebrow,        title,        introText,        testimonials[]{ _key, name, quote, label }      },      _type == "contact" => {        eyebrow,        title,        introText,        details[]{ _key, label, text, href, "iconUrl": icon.asset->url }      }    }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      sections: null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "about";
            eyebrow: string | null;
            title: string | null;
            body: Array<{
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal";
              listItem?: never;
              markDefs?: null;
              level?: number;
              _type: "block";
              _key: string;
            }> | null;
            listTitle: string | null;
            credentials: Array<string> | null;
            image: {
              alt: string | null;
              caption: string | null;
              asset: SanityImageAssetReference | null;
            } | null;
          }
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "firstWeeks";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            steps: Array<{
              _key: string;
              marker: string | null;
              title: string | null;
              description: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "hero";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            ctas: Array<{
              _key: string;
              label: string | null;
              href: string | null;
            }> | null;
            image: {
              alt: string | null;
              name: string | null;
              role: string | null;
              asset: SanityImageAssetReference | null;
            } | null;
          }
        | {
            _key: string;
            _type: "method";
            eyebrow: string | null;
            title: string | null;
            sideNote: string | null;
            methods: Array<{
              _key: string;
              title: string | null;
              description: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "proof";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            testimonials: Array<{
              _key: string;
              name: string | null;
              quote: string | null;
              label: string | null;
            }> | null;
          }
      > | null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "aboutHero";
          }
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "credentials";
          }
        | {
            _key: string;
            _type: "method";
            eyebrow: string | null;
            title: string | null;
            sideNote: string | null;
            methods: Array<{
              _key: string;
              title: string | null;
              description: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "myStory";
          }
        | {
            _key: string;
            _type: "principles";
          }
      > | null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "included";
          }
        | {
            _key: string;
            _type: "offerings";
          }
        | {
            _key: string;
            _type: "servicesHero";
          }
      > | null;
    }
  | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{    sections[]{      _key,      _type,      _type == "aboutHero" => {        eyebrow,        title,        titleHighlight,        introText,        cta{ label, href },        image{ alt, name, detail, asset }      },      _type == "myStory" => {        eyebrow,        title,        body,        quote,        quoteLabel      },      _type == "method" => {        eyebrow,        title,        sideNote,        methods[]{ _key, title, description }      },      _type == "principles" => {        eyebrow,        title,        introText,        principles[]{ _key, label, title, description }      },      _type == "credentials" => {        eyebrow,        title,        introText,        credentials[]{ _key, title, description }      },      _type == "contact" => {        eyebrow,        title,        introText,        details[]{ _key, label, text, href, "iconUrl": icon.asset->url }      }    }  }
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      sections: null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "about";
          }
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "firstWeeks";
          }
        | {
            _key: string;
            _type: "hero";
          }
        | {
            _key: string;
            _type: "method";
            eyebrow: string | null;
            title: string | null;
            sideNote: string | null;
            methods: Array<{
              _key: string;
              title: string | null;
              description: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "proof";
          }
      > | null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "aboutHero";
            eyebrow: string | null;
            title: string | null;
            titleHighlight: string | null;
            introText: string | null;
            cta: {
              label: string | null;
              href: string | null;
            } | null;
            image: {
              alt: string | null;
              name: string | null;
              detail: string | null;
              asset: SanityImageAssetReference | null;
            } | null;
          }
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "credentials";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            credentials: Array<{
              _key: string;
              title: string | null;
              description: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "method";
            eyebrow: string | null;
            title: string | null;
            sideNote: string | null;
            methods: Array<{
              _key: string;
              title: string | null;
              description: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "myStory";
            eyebrow: string | null;
            title: string | null;
            body: Array<{
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "normal";
              listItem?: never;
              markDefs?: null;
              level?: number;
              _type: "block";
              _key: string;
            }> | null;
            quote: string | null;
            quoteLabel: string | null;
          }
        | {
            _key: string;
            _type: "principles";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            principles: Array<{
              _key: string;
              label: string | null;
              title: string | null;
              description: string | null;
            }> | null;
          }
      > | null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "included";
          }
        | {
            _key: string;
            _type: "offerings";
          }
        | {
            _key: string;
            _type: "servicesHero";
          }
      > | null;
    }
  | null;

// Source: ../web/src/sanity/lib/queries.ts
// Variable: SERVICES_PAGE_QUERY
// Query: *[_id == "servicesPage"][0]{    sections[]{      _key,      _type,      _type == "servicesHero" => {        eyebrow,        title,        titleHighlight,        introText,        ctas[]{ _key, label, href },        "teaser": ^.sections[_type == "offerings"][0].offerings[].title      },      _type == "offerings" => {        eyebrow,        title,        introText,        offerings[]{ _key, tag, title, description, features }      },      _type == "included" => {        eyebrow,        title,        introText,        items      },      _type == "contact" => {        eyebrow,        title,        introText,        details[]{ _key, label, text, href, "iconUrl": icon.asset->url }      }    }  }
export type SERVICES_PAGE_QUERY_RESULT =
  | {
      sections: null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "about";
          }
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "firstWeeks";
          }
        | {
            _key: string;
            _type: "hero";
          }
        | {
            _key: string;
            _type: "method";
          }
        | {
            _key: string;
            _type: "proof";
          }
      > | null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "aboutHero";
          }
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "credentials";
          }
        | {
            _key: string;
            _type: "method";
          }
        | {
            _key: string;
            _type: "myStory";
          }
        | {
            _key: string;
            _type: "principles";
          }
      > | null;
    }
  | {
      sections: Array<
        | {
            _key: string;
            _type: "contact";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            details: Array<{
              _key: string;
              label: string | null;
              text: string | null;
              href: string | null;
              iconUrl: string | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "included";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            items: Array<string> | null;
          }
        | {
            _key: string;
            _type: "offerings";
            eyebrow: string | null;
            title: string | null;
            introText: string | null;
            offerings: Array<{
              _key: string;
              tag: string | null;
              title: string | null;
              description: string | null;
              features: Array<string> | null;
            }> | null;
          }
        | {
            _key: string;
            _type: "servicesHero";
            eyebrow: string | null;
            title: string | null;
            titleHighlight: string | null;
            introText: string | null;
            ctas: Array<{
              _key: string;
              label: string | null;
              href: string | null;
            }> | null;
            teaser: Array<string | null> | null;
          }
      > | null;
    }
  | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    logo{ alt, "url": asset->url },\n    navLinks[]{ _key, label, href },\n    contactButton{ label, href }\n  }\n': NAV_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    sections[]{\n      _key,\n      _type,\n      _type == "hero" => {\n        eyebrow,\n        title,\n        introText,\n        ctas[]{ _key, label, href },\n        image{ alt, name, role, asset }\n      },\n      _type == "about" => {\n        eyebrow,\n        title,\n        body,\n        listTitle,\n        credentials,\n        image{ alt, caption, asset }\n      },\n      _type == "firstWeeks" => {\n        eyebrow,\n        title,\n        introText,\n        steps[]{ _key, marker, title, description }\n      },\n      _type == "method" => {\n        eyebrow,\n        title,\n        sideNote,\n        methods[]{ _key, title, description }\n      },\n      _type == "proof" => {\n        eyebrow,\n        title,\n        introText,\n        testimonials[]{ _key, name, quote, label }\n      },\n      _type == "contact" => {\n        eyebrow,\n        title,\n        introText,\n        details[]{ _key, label, text, href, "iconUrl": icon.asset->url }\n      }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "aboutPage"][0]{\n    sections[]{\n      _key,\n      _type,\n      _type == "aboutHero" => {\n        eyebrow,\n        title,\n        titleHighlight,\n        introText,\n        cta{ label, href },\n        image{ alt, name, detail, asset }\n      },\n      _type == "myStory" => {\n        eyebrow,\n        title,\n        body,\n        quote,\n        quoteLabel\n      },\n      _type == "method" => {\n        eyebrow,\n        title,\n        sideNote,\n        methods[]{ _key, title, description }\n      },\n      _type == "principles" => {\n        eyebrow,\n        title,\n        introText,\n        principles[]{ _key, label, title, description }\n      },\n      _type == "credentials" => {\n        eyebrow,\n        title,\n        introText,\n        credentials[]{ _key, title, description }\n      },\n      _type == "contact" => {\n        eyebrow,\n        title,\n        introText,\n        details[]{ _key, label, text, href, "iconUrl": icon.asset->url }\n      }\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_id == "servicesPage"][0]{\n    sections[]{\n      _key,\n      _type,\n      _type == "servicesHero" => {\n        eyebrow,\n        title,\n        titleHighlight,\n        introText,\n        ctas[]{ _key, label, href },\n        "teaser": ^.sections[_type == "offerings"][0].offerings[].title\n      },\n      _type == "offerings" => {\n        eyebrow,\n        title,\n        introText,\n        offerings[]{ _key, tag, title, description, features }\n      },\n      _type == "included" => {\n        eyebrow,\n        title,\n        introText,\n        items\n      },\n      _type == "contact" => {\n        eyebrow,\n        title,\n        introText,\n        details[]{ _key, label, text, href, "iconUrl": icon.asset->url }\n      }\n    }\n  }\n': SERVICES_PAGE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
